.TH NTED 1 "September 30, 2007"
.SH NAME
NtEd \- A WYSIWYG Musical Score Editor
.SH SYNOPSIS
.B nted
.RI "[file]"
.SH DESCRIPTION
This manual page documents briefly the
.B nted
command.
.PP
\fBnted\fP is a WYSIWYG musical score editor for Linux. \fBnted\fP may
be started with no parameter to start a new score, or with a filename
to edit an existing score.
.PP
A detailed documentation is available at
http://vsr.informatik.tu-chemnitz.de/staff/jan/nted/nted.xhtml
.SH AUTHOR
NtEd was written by J\[:o]rg Anders.
.PP
This manual page was written by Gilles Filippini <gilles.filippini@free.fr>
and J\[:o]rg Anders <ja@informatik.tu-chemnitz.de>

